-- Marketplace Sales Dashboard - Supabase schema
-- Execute este arquivo no SQL Editor do Supabase uma vez.

create extension if not exists pgcrypto;

create table if not exists public.imports (
  id uuid primary key default gen_random_uuid(),
  marketplace text not null,
  file_name text not null,
  file_hash text not null,
  storage_path text,
  period_start date,
  period_end date,
  row_count integer not null default 0,
  unit_count numeric not null default 0,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  constraint imports_marketplace_hash_unique unique (marketplace, file_hash)
);

create table if not exists public.sales_items (
  id bigint generated by default as identity primary key,
  import_id uuid not null references public.imports(id) on delete cascade,
  marketplace text not null,
  order_id text,
  sale_date date,
  sku text not null,
  sku_original text,
  product text,
  variation text,
  listing_id text,
  status text,
  return_status text,
  units_original numeric not null default 0,
  units_cancelled numeric not null default 0,
  units_sold numeric not null default 0,
  units_returned numeric not null default 0,
  units_return_pending numeric not null default 0,
  units_net numeric not null default 0,
  sku_pending boolean not null default false,
  aggregate_period boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists sales_items_sale_date_idx on public.sales_items (sale_date);
create index if not exists sales_items_sku_idx on public.sales_items (sku);
create index if not exists sales_items_marketplace_idx on public.sales_items (marketplace);
create index if not exists sales_items_import_id_idx on public.sales_items (import_id);
create index if not exists imports_period_idx on public.imports (period_start, period_end);

alter table public.imports enable row level security;
alter table public.sales_items enable row level security;

drop policy if exists "authenticated users can read imports" on public.imports;
drop policy if exists "authenticated users can insert imports" on public.imports;
drop policy if exists "authenticated users can update imports" on public.imports;
drop policy if exists "authenticated users can delete imports" on public.imports;
create policy "authenticated users can read imports" on public.imports for select to authenticated using (true);
create policy "authenticated users can insert imports" on public.imports for insert to authenticated with check ((select auth.uid()) = created_by);
create policy "authenticated users can update imports" on public.imports for update to authenticated using (true) with check (true);
create policy "authenticated users can delete imports" on public.imports for delete to authenticated using (true);

drop policy if exists "authenticated users can read sales" on public.sales_items;
drop policy if exists "authenticated users can insert sales" on public.sales_items;
drop policy if exists "authenticated users can update sales" on public.sales_items;
drop policy if exists "authenticated users can delete sales" on public.sales_items;
create policy "authenticated users can read sales" on public.sales_items for select to authenticated using (true);
create policy "authenticated users can insert sales" on public.sales_items for insert to authenticated with check (true);
create policy "authenticated users can update sales" on public.sales_items for update to authenticated using (true) with check (true);
create policy "authenticated users can delete sales" on public.sales_items for delete to authenticated using (true);

grant select, insert, update, delete on public.imports to authenticated;
grant select, insert, update, delete on public.sales_items to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Bucket privado para guardar os arquivos originais.
insert into storage.buckets (id, name, public)
values ('marketplace-files', 'marketplace-files', false)
on conflict (id) do update set public = false;

drop policy if exists "authenticated can read marketplace files" on storage.objects;
drop policy if exists "authenticated can upload marketplace files" on storage.objects;
drop policy if exists "authenticated can update marketplace files" on storage.objects;
drop policy if exists "authenticated can delete marketplace files" on storage.objects;
create policy "authenticated can read marketplace files" on storage.objects for select to authenticated using (bucket_id = 'marketplace-files');
create policy "authenticated can upload marketplace files" on storage.objects for insert to authenticated with check (bucket_id = 'marketplace-files');
create policy "authenticated can update marketplace files" on storage.objects for update to authenticated using (bucket_id = 'marketplace-files') with check (bucket_id = 'marketplace-files');
create policy "authenticated can delete marketplace files" on storage.objects for delete to authenticated using (bucket_id = 'marketplace-files');

-- Resumo agregado no banco. Para Amazon, o relatório entra apenas quando o período
-- selecionado for exatamente igual ao período informado no momento da importação.
create or replace function public.get_sales_summary(p_start date, p_end date)
returns table (
  sku text,
  produto text,
  variacao text,
  tiktok_liquido numeric,
  mercado_livre_liquido numeric,
  shopee_liquido numeric,
  shein_liquido numeric,
  amazon_pedidas numeric,
  droga_raia_liquido numeric,
  magazine_luiza_liquido numeric,
  beleza_na_web_liquido numeric,
  total_considerado numeric,
  media_dia numeric,
  pedido_sugerido bigint,
  sku_pendente boolean
)
language sql
stable
security invoker
set search_path = public
as $$
  with eligible as (
    select s.*
    from public.sales_items s
    join public.imports i on i.id = s.import_id
    where
      (not s.aggregate_period and s.sale_date between p_start and p_end)
      or
      (s.aggregate_period and i.period_start = p_start and i.period_end = p_end)
  ), agg as (
    select
      e.sku,
      max(nullif(e.product, '')) as produto,
      max(nullif(e.variation, '')) as variacao,
      coalesce(sum(case when e.marketplace = 'TikTok' then e.units_net else 0 end),0) as tiktok_liquido,
      coalesce(sum(case when e.marketplace = 'Mercado Livre' then e.units_net else 0 end),0) as mercado_livre_liquido,
      coalesce(sum(case when e.marketplace = 'Shopee' then e.units_net else 0 end),0) as shopee_liquido,
      coalesce(sum(case when e.marketplace = 'SHEIN' then e.units_net else 0 end),0) as shein_liquido,
      coalesce(sum(case when e.marketplace = 'Amazon' then e.units_net else 0 end),0) as amazon_pedidas,
      coalesce(sum(case when e.marketplace = 'Droga Raia' then e.units_net else 0 end),0) as droga_raia_liquido,
      coalesce(sum(case when e.marketplace = 'Magazine Luiza' then e.units_net else 0 end),0) as magazine_luiza_liquido,
      coalesce(sum(case when e.marketplace = 'Beleza na Web' then e.units_net else 0 end),0) as beleza_na_web_liquido,
      bool_or(e.sku_pending) as sku_pendente
    from eligible e
    group by e.sku
  ), totals as (
    select a.*,
      (a.tiktok_liquido + a.mercado_livre_liquido + a.shopee_liquido + a.shein_liquido + a.amazon_pedidas + a.droga_raia_liquido + a.magazine_luiza_liquido + a.beleza_na_web_liquido) as total_considerado
    from agg a
  )
  select
    t.sku, t.produto, t.variacao,
    t.tiktok_liquido, t.mercado_livre_liquido, t.shopee_liquido, t.shein_liquido,
    t.amazon_pedidas, t.droga_raia_liquido, t.magazine_luiza_liquido, t.beleza_na_web_liquido,
    t.total_considerado,
    round(t.total_considerado / greatest(1, (p_end - p_start + 1)), 0) as media_dia,
    ceil(t.total_considerado * 1.15)::bigint as pedido_sugerido,
    t.sku_pendente
  from totals t
  order by t.total_considerado desc, t.sku;
$$;

grant execute on function public.get_sales_summary(date, date) to authenticated;

create or replace function public.get_pending_skus(p_start date, p_end date)
returns table (
  marketplace text,
  identificador text,
  produto text,
  variacao text,
  unidades_vendidas numeric
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    s.marketplace,
    coalesce(nullif(s.listing_id,''), nullif(s.order_id,''), '-') as identificador,
    max(nullif(s.product,'')) as produto,
    max(nullif(s.variation,'')) as variacao,
    sum(s.units_sold) as unidades_vendidas
  from public.sales_items s
  join public.imports i on i.id = s.import_id
  where s.sku_pending
    and (
      (not s.aggregate_period and s.sale_date between p_start and p_end)
      or
      (s.aggregate_period and i.period_start = p_start and i.period_end = p_end)
    )
  group by s.marketplace, coalesce(nullif(s.listing_id,''), nullif(s.order_id,''), '-')
  order by unidades_vendidas desc, marketplace;
$$;

grant execute on function public.get_pending_skus(date, date) to authenticated;
